/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/executive/tickets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Executive Tickets */
        get: operations["executive_tickets_api_v1_executive_tickets_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_api_v1_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_api_v1_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session */
        post: operations["create_session_api_v1_kiosk_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Status */
        get: operations["get_session_status_api_v1_kiosk_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/sessions/{session_id}/confirmation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_v1_kiosk_sessions__session_id__confirmation_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/sessions/{session_id}/conversation/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Conversation */
        post: operations["sync_conversation_api_v1_kiosk_sessions__session_id__conversation_messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/sessions/{session_id}/identification": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Identify */
        post: operations["identify_api_v1_kiosk_sessions__session_id__identification_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kiosk/sessions/{session_id}/turns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Turn */
        post: operations["analyze_turn_api_v1_kiosk_sessions__session_id__turns_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cases */
        get: operations["cases_api_v1_management_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/executives/{executive_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Executive Status */
        patch: operations["update_executive_status_api_v1_management_executives__executive_id__status_patch"];
        trace?: never;
    };
    "/api/v1/management/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Documents */
        get: operations["list_documents_api_v1_management_knowledge_documents_get"];
        put?: never;
        /** Create Document */
        post: operations["create_document_api_v1_management_knowledge_documents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/knowledge/documents/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_management_knowledge_documents_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/knowledge/documents/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_v1_management_knowledge_documents_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/knowledge/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Document */
        get: operations["get_document_api_v1_management_knowledge_documents__document_id__get"];
        put?: never;
        post?: never;
        /** Archive Document */
        delete: operations["archive_document_api_v1_management_knowledge_documents__document_id__delete"];
        options?: never;
        head?: never;
        /** Update Document */
        patch: operations["update_document_api_v1_management_knowledge_documents__document_id__patch"];
        trace?: never;
    };
    "/api/v1/management/knowledge/documents/{document_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Document */
        get: operations["download_document_api_v1_management_knowledge_documents__document_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/knowledge/documents/{document_id}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reindex Document */
        post: operations["reindex_document_api_v1_management_knowledge_documents__document_id__reindex_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/knowledge/documents/{document_id}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Document Version */
        post: operations["create_document_version_api_v1_management_knowledge_documents__document_id__versions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_api_v1_management_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/management/tickets/{ticket_id}/assignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ticket Assignment */
        patch: operations["update_ticket_assignment_api_v1_management_tickets__ticket_id__assignment_patch"];
        trace?: never;
    };
    "/api/v1/management/tickets/{ticket_id}/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Raise Ticket Priority */
        patch: operations["raise_ticket_priority_api_v1_management_tickets__ticket_id__priority_patch"];
        trace?: never;
    };
    "/api/v1/system/public-config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Config */
        get: operations["public_config_api_v1_system_public_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ticket Detail */
        get: operations["ticket_detail_api_v1_tickets__ticket_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/identifier/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reveal Identifier */
        post: operations["reveal_identifier_api_v1_tickets__ticket_id__identifier_reveal_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tickets/{ticket_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Ticket Status */
        patch: operations["update_ticket_status_api_v1_tickets__ticket_id__status_patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_document_api_v1_management_knowledge_documents_post */
        Body_create_document_api_v1_management_knowledge_documents_post: {
            /** Categories */
            categories: string;
            /** File */
            file: string;
            /** Review After */
            review_after?: string | null;
            /** Slug */
            slug: string;
            source_type: components["schemas"]["KnowledgeSourceType"];
            /**
             * Source Urls
             * @default []
             */
            source_urls: string;
            /** Title */
            title: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            /** Version */
            version: string;
        };
        /** Body_create_document_version_api_v1_management_knowledge_documents__document_id__versions_post */
        Body_create_document_version_api_v1_management_knowledge_documents__document_id__versions_post: {
            /** File */
            file: string;
            /** Review After */
            review_after?: string | null;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            /** Version */
            version: string;
        };
        /**
         * Category
         * @enum {string}
         */
        Category: "BLOQUEO_TARJETA" | "REPORTE_FRAUDE" | "CONSULTA_GENERAL" | "SOLICITUD_CREDITO" | "BANCA_DIGITAL";
        /** ConfirmationRequest */
        ConfirmationRequest: {
            /** Confirmed */
            confirmed: boolean;
            /**
             * Requirement Id
             * Format: uuid
             */
            requirement_id: string;
        };
        /**
         * ConsultationLevel
         * @enum {string}
         */
        ConsultationLevel: "GENERAL" | "PERSONALIZADA" | "SENSIBLE";
        /** ConversationMessageInput */
        ConversationMessageInput: {
            /** Item Id */
            item_id: string;
            role: components["schemas"]["ConversationRole"];
            /** Text */
            text: string;
        };
        /** ConversationMessageOut */
        ConversationMessageOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["ConversationRole"];
            /** Text */
            text: string;
        };
        /**
         * ConversationRole
         * @enum {string}
         */
        ConversationRole: "CUSTOMER" | "ASSISTANT";
        /** ConversationSyncRequest */
        ConversationSyncRequest: {
            /** Messages */
            messages: components["schemas"]["ConversationMessageInput"][];
        };
        /** ConversationSyncResponse */
        ConversationSyncResponse: {
            /** Accepted */
            accepted: number;
        };
        /** ExecutiveAssignment */
        ExecutiveAssignment: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Title */
            title: string;
            /** Window Number */
            window_number: string;
        };
        /**
         * ExecutiveStatus
         * @enum {string}
         */
        ExecutiveStatus: "DISPONIBLE" | "OCUPADO" | "INACTIVO";
        /** ExecutiveStatusResult */
        ExecutiveStatusResult: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ExecutiveStatus"];
            /**
             * Unassigned Tickets
             * @default 0
             */
            unassigned_tickets: number;
            /** Version */
            version: number;
        };
        /** ExecutiveStatusUpdate */
        ExecutiveStatusUpdate: {
            /** Expected Version */
            expected_version: number;
            status: components["schemas"]["ExecutiveStatus"];
        };
        /** ExecutiveWorkload */
        ExecutiveWorkload: {
            /** Closed */
            closed: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** In Attention */
            in_attention: number;
            /** Name */
            name: string;
            /** Pending */
            pending: number;
            status: components["schemas"]["ExecutiveStatus"];
            /** Title */
            title: string;
            /** Version */
            version: number;
        };
        /** FlowResult */
        FlowResult: {
            /** Citations */
            citations?: components["schemas"]["KnowledgeCitation"][];
            /** Customer Summary */
            customer_summary?: string | null;
            executive?: components["schemas"]["ExecutiveAssignment"] | null;
            /** @default NOT_APPLICABLE */
            grounding_status: components["schemas"]["GroundingStatus"];
            identification_status?: components["schemas"]["IdentificationStatus"] | null;
            /**
             * Next Action
             * @enum {string}
             */
            next_action: "CAPTURE" | "IDENTIFY" | "COMPLETE";
            priority?: components["schemas"]["Priority"] | null;
            /**
             * Requirement Id
             * Format: uuid
             */
            requirement_id: string;
            resolution_type?: components["schemas"]["ResolutionType"] | null;
            /** Response */
            response?: string | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Speech Text */
            speech_text: string;
            status: components["schemas"]["SessionStatus"];
            ticket?: components["schemas"]["TicketResult"] | null;
            /** Tracking Information */
            tracking_information?: string | null;
        };
        /**
         * GroundingStatus
         * @enum {string}
         */
        GroundingStatus: "GROUNDED" | "NO_EVIDENCE" | "NOT_APPLICABLE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourlyMetric */
        HourlyMetric: {
            /** Cases */
            cases: number;
            /** Hour */
            hour: string;
        };
        /** IdentificationRequest */
        IdentificationRequest: {
            /** Identifier */
            identifier: string;
        };
        /**
         * IdentificationStatus
         * @enum {string}
         */
        IdentificationStatus: "ANONIMO" | "PENDIENTE" | "IDENTIFICADO" | "FALLIDO" | "VERIFICACION_MANUAL";
        /** IdentifierRevealResponse */
        IdentifierRevealResponse: {
            /** Identifier */
            identifier: string;
            /**
             * Reveal Seconds
             * @default 30
             */
            reveal_seconds: number;
        };
        /** KnowledgeCitation */
        KnowledgeCitation: {
            /**
             * Chunk Id
             * Format: uuid
             */
            chunk_id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Page */
            page: number;
            /** Score */
            score: number;
            /** Section */
            section?: string | null;
            /** Source Url */
            source_url?: string | null;
            /** Title */
            title: string;
        };
        /** KnowledgeDocumentPage */
        KnowledgeDocumentPage: {
            /** Items */
            items: components["schemas"]["KnowledgeDocumentSummary"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** KnowledgeDocumentSummary */
        KnowledgeDocumentSummary: {
            /** Active */
            active: boolean;
            /** Byte Size */
            byte_size: number;
            /** Categories */
            categories: components["schemas"]["Category"][];
            /** Chunk Count */
            chunk_count: number;
            /** Content Sha256 */
            content_sha256: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** File Name */
            file_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Index Error */
            index_error: string | null;
            index_status: components["schemas"]["KnowledgeIndexStatus"];
            /** Indexed At */
            indexed_at: string | null;
            /** Mime Type */
            mime_type: string;
            /** Page Count */
            page_count: number;
            /** Review After */
            review_after: string | null;
            /** Slug */
            slug: string;
            source_type: components["schemas"]["KnowledgeSourceType"];
            /** Source Urls */
            source_urls: string[];
            /** Title */
            title: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /**
             * Verified At
             * Format: date-time
             */
            verified_at: string;
            /** Version */
            version: string;
        };
        /** KnowledgeDocumentUpdate */
        KnowledgeDocumentUpdate: {
            /** Active */
            active?: boolean | null;
            /** Categories */
            categories?: components["schemas"]["Category"][] | null;
            /** Review After */
            review_after?: string | null;
            source_type?: components["schemas"]["KnowledgeSourceType"] | null;
            /** Source Urls */
            source_urls?: string[] | null;
            /** Title */
            title?: string | null;
            /** Verified At */
            verified_at?: string | null;
        };
        /**
         * KnowledgeIndexStatus
         * @enum {string}
         */
        KnowledgeIndexStatus: "PENDING" | "INDEXING" | "READY" | "FAILED" | "ARCHIVED";
        /**
         * KnowledgeJobOperation
         * @enum {string}
         */
        KnowledgeJobOperation: "CREATE" | "VERSION" | "REINDEX";
        /** KnowledgeJobResponse */
        KnowledgeJobResponse: {
            document: components["schemas"]["KnowledgeDocumentSummary"];
            job: components["schemas"]["KnowledgeJobSummary"];
        };
        /**
         * KnowledgeJobStatus
         * @enum {string}
         */
        KnowledgeJobStatus: "QUEUED" | "RUNNING" | "SUCCEEDED" | "FAILED";
        /** KnowledgeJobSummary */
        KnowledgeJobSummary: {
            /** Attempts */
            attempts: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /** Error Code */
            error_code: string | null;
            /** Error Message */
            error_message: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Max Attempts */
            max_attempts: number;
            operation: components["schemas"]["KnowledgeJobOperation"];
            /** Started At */
            started_at: string | null;
            status: components["schemas"]["KnowledgeJobStatus"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * KnowledgeSourceType
         * @enum {string}
         */
        KnowledgeSourceType: "OFFICIAL" | "REGULATORY" | "INTERNAL" | "HYBRID";
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** ManagementCasesResponse */
        ManagementCasesResponse: {
            /** Items */
            items: components["schemas"]["ManagerialCase"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Total */
            total: number;
        };
        /** ManagementMetrics */
        ManagementMetrics: {
            /** Active Cases */
            active_cases: number;
            /** Automatic Resolution Rate */
            automatic_resolution_rate: number;
            /** Automatic Resolved */
            automatic_resolved: number;
            /** Average Attention Minutes */
            average_attention_minutes: number;
            /** Average Wait Minutes */
            average_wait_minutes: number;
            /** By Category */
            by_category: components["schemas"]["MetricSlice"][];
            /** By Priority */
            by_priority: components["schemas"]["MetricSlice"][];
            /** Closed Cases */
            closed_cases: number;
            /** Critical Pending */
            critical_pending: number;
            /** Executives */
            executives: components["schemas"]["ExecutiveWorkload"][];
            /** Hourly */
            hourly: components["schemas"]["HourlyMetric"][];
            /** Human Routed */
            human_routed: number;
            /** In Attention Cases */
            in_attention_cases: number;
            /** Oldest Pending Minutes */
            oldest_pending_minutes: number;
            /** Pending Cases */
            pending_cases: number;
            /** Total Cases */
            total_cases: number;
            /** Unassigned Cases */
            unassigned_cases: number;
            /** Wait P50 Minutes */
            wait_p50_minutes: number;
            /** Wait P95 Minutes */
            wait_p95_minutes: number;
        };
        /** ManagementTicketMutation */
        ManagementTicketMutation: {
            /** Executive Id */
            executive_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: string;
            priority: components["schemas"]["Priority"];
            status: components["schemas"]["TicketStatus"];
            /** Version */
            version: number;
        };
        /** ManagerialCase */
        ManagerialCase: {
            /** Attention Time Min */
            attention_time_min: number | null;
            category: components["schemas"]["Category"];
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Executive */
            executive: string | null;
            /** Executive Id */
            executive_id: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            priority: components["schemas"]["Priority"];
            resolution_outcome: components["schemas"]["ResolutionOutcome"] | null;
            status: components["schemas"]["TicketStatus"];
            /** Summary */
            summary: string;
            /** Ticket */
            ticket: string;
            /** Version */
            version: number;
            /** Wait Time Min */
            wait_time_min: number;
        };
        /** MetricSlice */
        MetricSlice: {
            /** Name */
            name: string;
            /** Value */
            value: number;
        };
        /**
         * Priority
         * @enum {string}
         */
        Priority: "CRITICO" | "ALTO" | "MEDIO" | "BAJO";
        /** ProtectedIdentity */
        ProtectedIdentity: {
            /** Display Name */
            display_name?: string | null;
            /** Masked Identifier */
            masked_identifier?: string | null;
            /**
             * Reveal Available
             * @default false
             */
            reveal_available: boolean;
            status: components["schemas"]["IdentificationStatus"];
        };
        /** PublicSystemConfig */
        PublicSystemConfig: {
            /** App Name */
            app_name: string;
            /** Bank Name */
            bank_name: string;
            /** Branch Name */
            branch_name: string;
            /** Conversation Retention Days */
            conversation_retention_days: number;
            /** Dashboard Refresh Ms */
            dashboard_refresh_ms: number;
        };
        /**
         * ResolutionOutcome
         * @enum {string}
         */
        ResolutionOutcome: "RESUELTO" | "DERIVADO" | "PENDIENTE_DOCUMENTACION" | "CLIENTE_DESISTIO" | "NO_RESUELTO";
        /**
         * ResolutionType
         * @enum {string}
         */
        ResolutionType: "AUTOMATIC" | "HUMAN";
        /** SessionCreateRequest */
        SessionCreateRequest: {
            /**
             * Preferential Attention
             * @default false
             */
            preferential_attention: boolean;
        };
        /** SessionCreatedResponse */
        SessionCreatedResponse: {
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            /** Session Token */
            session_token: string;
            status: components["schemas"]["SessionStatus"];
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "CREATED" | "LISTENING" | "NEEDS_CLARIFICATION" | "AWAITING_CONFIRMATION" | "AWAITING_IDENTIFICATION" | "ORCHESTRATING" | "RESOLVED_AUTOMATIC" | "ASSIGNED" | "DECLINED" | "FAILED";
        /** SessionStatusResponse */
        SessionStatusResponse: {
            analysis?: components["schemas"]["TurnAnalysisResponse"] | null;
            /** Final Response */
            final_response?: string | null;
            resolution_type?: components["schemas"]["ResolutionType"] | null;
            result?: components["schemas"]["FlowResult"] | null;
            /**
             * Session Id
             * Format: uuid
             */
            session_id: string;
            status: components["schemas"]["SessionStatus"];
        };
        /** TicketAssignmentUpdate */
        TicketAssignmentUpdate: {
            /** Executive Id */
            executive_id: string | null;
            /** Expected Version */
            expected_version: number;
            /** Reason */
            reason: string;
        };
        /** TicketDetail */
        TicketDetail: {
            category: components["schemas"]["Category"];
            /** Client Display Name */
            client_display_name?: string | null;
            /** Client Session Id */
            client_session_id: string;
            /** Closed At */
            closed_at?: string | null;
            consultation_level: components["schemas"]["ConsultationLevel"];
            /** Conversation */
            conversation: components["schemas"]["ConversationMessageOut"][];
            /** Estimated Wait Minutes */
            estimated_wait_minutes: number | null;
            /** Events */
            events: components["schemas"]["TraceEventOut"][];
            /** Executive Name */
            executive_name: string | null;
            /** Executive Title */
            executive_title: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            identification_status: components["schemas"]["IdentificationStatus"];
            identity: components["schemas"]["ProtectedIdentity"];
            /** Masked Identifier */
            masked_identifier?: string | null;
            /** Minutes Elapsed */
            minutes_elapsed: number;
            /** Number */
            number: string;
            /** Preferential Attention */
            preferential_attention: boolean;
            priority: components["schemas"]["Priority"];
            /** Resolution Note */
            resolution_note?: string | null;
            resolution_outcome?: components["schemas"]["ResolutionOutcome"] | null;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["TicketStatus"];
            /** Summary */
            summary: string;
            /** Time Assigned */
            time_assigned: string | null;
            /** Version */
            version: number;
            /** Wait Time Min */
            wait_time_min: number;
            /** Window Number */
            window_number: string | null;
        };
        /** TicketListItem */
        TicketListItem: {
            category: components["schemas"]["Category"];
            /** Client Display Name */
            client_display_name?: string | null;
            /** Client Session Id */
            client_session_id: string;
            /** Closed At */
            closed_at?: string | null;
            /** Estimated Wait Minutes */
            estimated_wait_minutes: number | null;
            /** Executive Name */
            executive_name: string | null;
            /** Executive Title */
            executive_title: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            identification_status: components["schemas"]["IdentificationStatus"];
            /** Masked Identifier */
            masked_identifier?: string | null;
            /** Minutes Elapsed */
            minutes_elapsed: number;
            /** Number */
            number: string;
            /** Preferential Attention */
            preferential_attention: boolean;
            priority: components["schemas"]["Priority"];
            resolution_outcome?: components["schemas"]["ResolutionOutcome"] | null;
            /** Started At */
            started_at?: string | null;
            status: components["schemas"]["TicketStatus"];
            /** Summary */
            summary: string;
            /** Time Assigned */
            time_assigned: string | null;
            /** Version */
            version: number;
            /** Wait Time Min */
            wait_time_min: number;
            /** Window Number */
            window_number: string | null;
        };
        /** TicketPage */
        TicketPage: {
            /** Items */
            items: components["schemas"]["TicketListItem"][];
            /** Page */
            page: number;
            /** Page Size */
            page_size: number;
            /** Status Counts */
            status_counts: {
                [key: string]: number;
            };
            /** Total */
            total: number;
        };
        /** TicketPriorityUpdate */
        TicketPriorityUpdate: {
            /** Expected Version */
            expected_version: number;
            priority: components["schemas"]["Priority"];
            /** Reason */
            reason: string;
        };
        /** TicketResult */
        TicketResult: {
            /** Estimated Wait Minutes */
            estimated_wait_minutes?: number | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Number */
            number: number;
            status: components["schemas"]["TicketStatus"];
        };
        /**
         * TicketStatus
         * @enum {string}
         */
        TicketStatus: "PENDIENTE" | "EN_ATENCION" | "CERRADO";
        /** TicketStatusUpdate */
        TicketStatusUpdate: {
            /** Expected Version */
            expected_version: number;
            /** Resolution Note */
            resolution_note?: string | null;
            resolution_outcome?: components["schemas"]["ResolutionOutcome"] | null;
            status: components["schemas"]["TicketStatus"];
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             * @constant
             */
            token_type: "bearer";
            user: components["schemas"]["UserSummary"];
        };
        /** TraceEventOut */
        TraceEventOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Description */
            description: string;
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
        };
        /** TurnAnalysisResponse */
        TurnAnalysisResponse: {
            category: components["schemas"]["Category"];
            /** Clarification Question */
            clarification_question?: string | null;
            /** Confidence */
            confidence: number;
            consultation_level: components["schemas"]["ConsultationLevel"];
            /** Customer Summary */
            customer_summary: string;
            /**
             * Next Action
             * @enum {string}
             */
            next_action: "CLARIFY" | "CONFIRM" | "DECLINE" | "COMPLETE";
            /** Pii Types */
            pii_types?: string[];
            priority: components["schemas"]["Priority"];
            /**
             * Requirement Id
             * Format: uuid
             */
            requirement_id: string;
            result?: components["schemas"]["FlowResult"] | null;
            /** Speech Text */
            speech_text: string;
            status: components["schemas"]["SessionStatus"];
            /** Summary */
            summary: string;
        };
        /** TurnRequest */
        TurnRequest: {
            /**
             * Is Clarification
             * @default false
             */
            is_clarification: boolean;
            /** Transcript */
            transcript: string;
            /**
             * Turn Id
             * Format: uuid
             */
            turn_id: string;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "EXECUTIVE" | "MANAGER";
        /** UserSummary */
        UserSummary: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Executive Id */
            executive_id?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            role: components["schemas"]["UserRole"];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                orquestacion_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSummary"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                orquestacion_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    executive_tickets_api_v1_executive_tickets_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["TicketStatus"] | null;
                category?: components["schemas"]["Category"] | null;
                priority?: components["schemas"]["Priority"] | null;
                q?: string | null;
                sort?: "priority" | "oldest" | "newest";
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_api_v1_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_api_v1_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_session_api_v1_kiosk_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreatedResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_status_api_v1_kiosk_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_kiosk_sessions__session_id__confirmation_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_conversation_api_v1_kiosk_sessions__session_id__conversation_messages_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConversationSyncRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSyncResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    identify_api_v1_kiosk_sessions__session_id__identification_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["IdentificationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_turn_api_v1_kiosk_sessions__session_id__turns_post: {
        parameters: {
            query?: never;
            header?: {
                "X-Session-Token"?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TurnRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cases_api_v1_management_cases_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                category?: components["schemas"]["Category"] | null;
                priority?: components["schemas"]["Priority"] | null;
                executive_id?: string | null;
                unassigned?: boolean | null;
                status?: components["schemas"]["TicketStatus"] | null;
                q?: string | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagementCasesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_executive_status_api_v1_management_executives__executive_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                executive_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExecutiveStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExecutiveStatusResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_documents_api_v1_management_knowledge_documents_get: {
        parameters: {
            query?: {
                search?: string | null;
                active?: boolean | null;
                index_status?: components["schemas"]["KnowledgeIndexStatus"] | null;
                page?: number;
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_api_v1_management_knowledge_documents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_document_api_v1_management_knowledge_documents_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_management_knowledge_documents_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_v1_management_knowledge_documents_jobs__job_id__retry_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_document_api_v1_management_knowledge_documents__document_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_document_api_v1_management_knowledge_documents__document_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_document_api_v1_management_knowledge_documents__document_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KnowledgeDocumentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeDocumentSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_document_api_v1_management_knowledge_documents__document_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reindex_document_api_v1_management_knowledge_documents__document_id__reindex_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_document_version_api_v1_management_knowledge_documents__document_id__versions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_document_version_api_v1_management_knowledge_documents__document_id__versions_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    metrics_api_v1_management_metrics_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                category?: components["schemas"]["Category"] | null;
                priority?: components["schemas"]["Priority"] | null;
                executive_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagementMetrics"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticket_assignment_api_v1_management_tickets__ticket_id__assignment_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketAssignmentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagementTicketMutation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    raise_ticket_priority_api_v1_management_tickets__ticket_id__priority_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketPriorityUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManagementTicketMutation"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    public_config_api_v1_system_public_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicSystemConfig"];
                };
            };
        };
    };
    ticket_detail_api_v1_tickets__ticket_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reveal_identifier_api_v1_tickets__ticket_id__identifier_reveal_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdentifierRevealResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_ticket_status_api_v1_tickets__ticket_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                ticket_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TicketStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TicketDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
